// <auto-generated />
using System;
using ChatMicroservice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatMicroservice.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20250418151842_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatMicroservice.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatRoom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ChatMicroservice.Models.ChatMessage", b =>
                {
                    b.OwnsMany("ChatMicroservice.Models.Plan", "Plans", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Category")
                                .HasColumnType("text");

                            b1.HasKey("ChatMessageId", "Id");

                            b1.ToTable("MessagePlans", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageId");

                            b1.OwnsMany("ChatMicroservice.Models.Exercise", "Exercises", b2 =>
                                {
                                    b2.Property<Guid>("PlanChatMessageId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("PlanId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("MuscleGroup")
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PlanChatMessageId", "PlanId", "Id");

                                    b2.ToTable("PlanExercises", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PlanChatMessageId", "PlanId");
                                });

                            b1.Navigation("Exercises");
                        });

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
